params:
  mass: 13.5
  Jx: 0.8244
  Jy: 1.135
  Jz: 1.759
  Jxz: 0.1204
  S: 0.55
  b: 2.8956
  c: 0.18994
  S_prop: 0.2027
  rho: 1.2682
  k_motor: 80
  kT_p: 0
  kOmega: 0
  e: 0.9

longitudinal_coeffs:
  CL0: .28
  CD0: 0.03
  Cm0: -0.023338
  CL_alpha: 3.45
  CD_alpha: 0.30
  Cm_alpha: -0.38
  CL_q: 0.
  CD_q: 0.
  Cm_q: -3.6
  CL_delta_e: -0.36
  CD_delta_e: 0.0
  Cm_delta_e: -0.5
  C_prop: 1.0
  M: 50
  alpha_0: 0.4712
  epsilon: 0.1592
  CD_p: 0.0437

lateral_coeffs:
  CY0: 0.
  Cl0: 0.
  Cn0: 0.
  CY_beta: -0.98
  Cl_beta: -0.12
  Cn_beta: 0.25
  CY_p: 0.
  Cl_p: -0.26
  Cn_p: 0.022
  CY_r: 0.
  Cl_r: 0.14
  Cn_r: -0.35
  CY_delta_a: 0.
  Cl_delta_a: 0.08
  Cn_delta_a: 0.06
  CY_delta_r: -0.17
  Cl_delta_r: 0.105
  Cn_delta_r: -0.032

autopilot:
  delta_a_max_deg: 45
  error_phi_max_deg: 15
  delta_e_max_deg: 45
  error_theta_max_deg: 10
  roll:
    ki: 5
    tau: 0.05
    zeta: 1.5
  pitch:
    ki: 0
    tau: 0.05
    zeta: 0.7
  airspeed:
    pitch:
      zeta: .75
    throttle:
      zeta: 0.05
  altitude:
    pitch:
      zeta: 1.0

  